# Generated by Django 4.1.5 on 2023-01-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='firstname',
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(db_column='first_name', default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='lastname',
            field=models.CharField(db_column='last_name', max_length=128),
        ),
    ]
