# Generated by Django 4.1.5 on 2023-01-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0002_remove_person_firstname_person_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
