# Generated by Django 4.1.5 on 2023-01-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0003_rename_lastname_person_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Polygender', 'P')], db_column='gender', max_length=10),
        ),
    ]
