# Generated by Django 4.1.5 on 2023-01-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0005_alter_person_gender'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='companies',
        ),
    ]
